name: Greet the User
on:
  push:  # This is the "Event Trigger" that is missing!
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a greeting
        run: echo "The code has been pushed!"
      - name: Give me the OS version
        run: cat /etc/os-release
  system-info:
    name: Check Network and Kernel
    runs-on: macos-latest  # Using a different OS!
    steps:
      - name: Show Network Config
        run: ifconfig
        
      - name: Show System Controls
        run: sysctl -a | grep machdep.cpu.brand_string 
  # This job waits for BOTH say-hello and system-info
  report-status:
    needs: [say-hello, system-info]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Both initial jobs passed. Reporting success!"

  # This job only waits for report-status
  archive-logs:
    needs: report-status
    runs-on: ubuntu-latest
    steps:
      - run: echo "Archiving the final results..."
